### ISSUE TITLE
Update docs to clarify requirements of seneca-basic

### ISSUE THREAD

**Issue by tswaters** [senecajs/seneca-user#76]
The [current docs on npm](https://www.npmjs.com/package/seneca-user), which are linked from senecajs.org do not mention the requirement for seneca-basic.  Using the example, as provided, results in the following cryptic explosion:

```
Seneca Fatal Error
==================

Message: seneca: No matching action pattern found for { list:    [ { entity: '-/sys/user', fields: [Object] },     { entity: '-/sys/login', fields: [] },     { entity: '-/sys/reset', fields: [] } ],  role: 'util',  cmd: 'define_sys_entity' }, and no default result provided (using a default$ property).

Code: act_not_found

Details: { args: '{ list:    [ { entity: \'-/sys/user\', fields: [Object] },     { entity: \'-/sys/login\', fields: [] },     { entity: \'-/sys/reset\', fields: [] } ],  role: \'util\',  cmd: \'define_sys_entity\' }' }

Stack:
    at Object.errormaker [as error] (C:\Code\seneca-tests\node_modules\eraro\eraro.js:94:15)
    at executable_action (C:\Code\seneca-tests\node_modules\seneca\seneca.js:1155:23)
    at execute_action (C:\Code\seneca-tests\node_modules\seneca\seneca.js:875:12)
    at Object.execspec.fn [as orig_fn] (C:\Code\seneca-tests\node_modules\seneca\seneca.js:1084:11)
    at Object.timeout_fn [as fn] (C:\Code\seneca-tests\node_modules\gate-executor\gate-executor.js:194:12)
    at next (C:\Code\seneca-tests\node_modules\gate-executor\gate-executor.js:126:14)
    at process (C:\Code\seneca-tests\node_modules\gate-executor\gate-executor.js:175:12)
    at Immediate.<anonymous> (C:\Code\seneca-tests\node_modules\gate-executor\gate-executor.js:258:7)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)

Instance: Seneca/2urn6ky9fqxp/1473197242606/17820/3.0.0/todo-user
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at executable_action (C:\Code\seneca-tests\node_modules\seneca\seneca.js:1160:22)

When: 2016-09-06T21:27:22.840Z

Log: {kind:null,plugin:seneca,tag:3.0.0,id:2urn6ky9fqxp/1473197242606/17820/3.0.0/todo-user,code:act_not_found,notic
```

And indeed, the current readme page doesn't really say much about it all outside of the quick example... I didn't even notice it until I looked through the README with a fine tooth comb.

**Comment by mihaidma** [comment]
Yes, as you say, the readme sample is updated, will appear on npm on next release version.
Please check also the tests, they can be used as a working code reference.

I'll add an explicit link to tests in the readme.

**Comment by mihaidma** [comment]
@tswaters updated again the docs. Thank you for the suggestions.
